### ISSUE TITLE
ace_fonts is outdated

### ISSUE THREAD

**Issue by throwaway4478** [Zakant/ACE3_Nightly#1]
Re-installed over and over again. Didn't get fixed. It says ace_fonts is outdated. I play with only CBA by the way.

**Comment by Zakant** [comment]
This repository is only for hosting the nigthly build logs. An bugs belong, as allready written in the [Readme](https://github.com/Zakant/ACE3_Nightly#need-help), into the [ACE 3 repsoitory](https://github.com/acemod/ACE3). Make sure to fill out the template **fully and correctly**. Especially include the correct commit hash and the rpt!
